### PR TITLE
Finalized md file for Shahrad

### PR DESCRIPTION
**Pull request by EMZEDI**
completed the md file for issue #53 .
-  Where am I supposed to upload the picture? 
 
Thanks

### CODE REVIEW

**Comment by napulen** [comment]
They go under `assets/lab_members`.

There are two pictures that should be included:

- Thumbnail: `assets/lab_members/thumbnail/`
- Full-size pic: `assets/lab_members/`

**Comment by napulen** [comment]
I'll wait for you to add the pictures then merge the request.

**Comment by EMZEDI** [comment]
Hello. Sorry for being so late I just noticed this issue has been open and I didn't fix it. I was wondering If it matters for the thumbnail to be the same as the photo?

**Comment by napulen** [comment]
> Hello. Sorry for being so late I just noticed this issue has been open and I didn't fix it. I was wondering If it matters for the thumbnail to be the same as the photo?

No problem if it is the same

**Review by napulen — APPROVED** [review]

**Comment by EMZEDI** [comment]
Thank you!!

**Pull request merged**
