### PR TITLE
Add 2023 group photo to front page

### PR DESCRIPTION
**Pull request by zhannaklimanova**

### CODE REVIEW

**Review by PythonSemicolon — COMMENTED** [review]
Looks ok. I believe the old photo will need to be added to the [archive](https://ddmal.music.mcgill.ca/people/) at `/people` now (@fujinaga can you confirm this).
Can you also replace the image in the `deforested` branch as it is the deployed version?

**Comment by zhannaklimanova** [comment]
> Looks ok. I believe the old photo will need to be added to the [archive](https://ddmal.music.mcgill.ca/people/) at `/people` now (@fujinaga can you confirm this). Can you also replace the image in the `deforested` branch as it is the deployed version?

Added photos to archive + deforested branch should also be updated. Review please.

**Review by PythonSemicolon — APPROVED** [review]
Looks good

**Comment by fujinaga** [comment]
> > Looks ok. I believe the old photo will need to be added to the [archive](https://ddmal.music.mcgill.ca/people/) at `/people` now (@fujinaga can you confirm this). Can you also replace the image in the `deforested` branch as it is the deployed version?
> 
> 
> 
> Added photos to archive + deforested branch should also be updated. Review both please.

Yes, I confirm.

**Pull request merged**
